sudo: required

language: c

services:
  - docker

before_install:
  - docker build -t chibitronics/ltc-webview-amd64:local .
  - docker run --name ltc-webview-node -d -p 127.0.0.1:80:80 chibitronics/ltc-webview-amd64:local
  - docker ps -a

script:
  - docker ps | grep ltc-webview-node
  - if [ "$TRAVIS_BRANCH" = "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    if [ -z "$TRAVIS_TAG" ]; then
    tagname=latest; else
    tagname=$TRAVIS_TAG;
    fi;
    docker tag chibitronics/ltc-webview-amd64:local chibitronics/ltc-webview-amd64:${tagname} &&
    docker push chibitronics/ltc-webview-amd64:${tagname};
    fi